config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  
  get 'home/about'=> 'homes#about', as: 'about'
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    
    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
  validates :name,length: { in: 2..20 },uniqueness: true
  validates :introduction, length: { maximum: 50 }
    
  def get_profile_image(w,h)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [w, h]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top,:about]

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Signed in successfully."
      redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end
  
  def destroy
    book = Book.find(params[:id]) 
    book.destroy
    redirect_to '/books'
  end
  
  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
    redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if  @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
  def controller
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end
  
  def index
    @user = User.find(current_user.id)
    @users = User.all
    @books = Book.all
    @book = Book.new
  end
  
  def destroy
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
    redirect_to user_path(current_user)
    end
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user),notice:"You have updated user successfully"
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to users_path
    end
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
 <div class="container">
  <div class = "row">
   <div class="col-md-8 offset-md-1">
    <h1>Editing Book</h1>
    <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
    <% end %>
    <%= form_with model: @book do |f| %>
    <div class ="form-group">
      <h2>Title</h2>
       <%= f.text_field :title %>
      
    <div class ="form-group">
      <h2>Opinion</h2>
      <%= f.text_area :body %>
    <div class ="form-group">
      <%= f.submit 'Update Book', class:"btn btn-success" %>
    <% end %>
  </div>
  <%= link_to 'Show', book_path(@book.id) %>|
    <%= link_to 'Back', books_path %>
 </div> 
 </div>
 <footer>
<p>CopyRight Infratop.inc</p>
</footer>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class ="row">
    <% if @book.errors.any? %>
  <%= @book.errors.count %>can't be blank
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
    <% end %>
    <div class="col-md-3">
      <h1>Users info</h1>
      <h3 class="profile-name"></h3>
      <%= image_tag current_user.get_profile_image(100,100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
      </table>
      
      <div class="row">
        <%= link_to edit_user_path(current_user.id) ,class:"btn btn-info btn-sm btn-block md-3" do %>
          <i class="fas fa-users"></i>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

      
      <!--<div class="col-md-3">-->
        
      <h3>New book</h3>
      
      <%= form_with model: @book do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        
        <%= f.submit 'Create Book', class:"btn btn-success"%>
      <% end %>
    </div>
    
    <!--</div>-->
    
    <div class="col-md-8 offset-md-1">
      <h5>Books</h5>
      
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(80,80) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<!-- ユーザーの投稿一覧 -->
<%#= render 'books/book', books: @books %>
<p>CopyRight Infratop.inc</p>

app/views/books/new.html.erb
<h1>New book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>更新に失敗しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
	
  <h4>本文</h4>
  <%= f.text_area :body %>
  
  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
	
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<!DOCTYPE html>
<div class="container px-5 px-sm-0">
  <div class = "row">
  <div class="col-md-3">
    <h1>Users info</h1>
    <h3 class="profile-name"></h3>
  <%= image_tag @user.get_profile_image(100,100) %>
  <table class="table">
   <tr>
    <th>name</th>
    <th><%= @user.name %></th>
    </tr>
      <tr>
    <th>introduction</th>
    <th><%= @user.introduction %></th>
    </tr>
  </table>
  <script src="https://kit.fontawesome.com/b88cbfadf5.js" crossorigin="anonymous"></script>
  <li class="nav-item">
    <%= link_to edit_user_path(@book.user.id), class:"btn btn-info btn-sm btn-block md-3" do %>
    <i class="fas fa-users"></i>
    <i class="fas fa-user-cog"></i>
    <% end %>
  </li>
  
  <!--<div class="col-md-3">-->
    <h3>New book</h3>
    <%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Opinion</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
  </div>
<!--</div>-->
<div class="col-md-8 offset-md-1">
  <h5>Book detail</h5>
  <table class="table table-hover table-inverse">
    <div>
  <td>
    <%= link_to user_path(@book.user) do %> 
      <%= image_tag @book.user.get_profile_image(80,80) %><br>
      <%= @book.user.name %>
    <% end %>
  </td>
  
  <td><p><%= @book.title %></p></td>
  <td><p><%= @book.body %></p></td>
  <% if @book.user_id == current_user.id %>
  <td><%= link_to "Edit", edit_book_path, class:"btn btn-sm btn-success" %></td>
  <td><%= link_to 'Destroy',book_path(@book.id), class:"btn btn-sm btn-danger",method: :delete, "data-confirm" => "本当に消しますか？" %></td>
  <% end %>
</div>
<p><%= @user.name %></p>
    <tr></tr>
  </table>
  </div>
 </div> 
 </div>
</div>
<!-- ユーザーの投稿一覧 -->
<%#= render 'books/book', books: @books %>

app/views/books/top.html.erb
<h1>ここはTopページです</h1>

app/views/homes/about.html.erb
<body>
<div class="container">
 <div class = "row">
  <div class="px-3 mx-suto">
<h1>Welcome to <i class="fas fa-book"></i>Bookers!</h1>
  </div>
 </div>
</div>
<footer>
 <div class="container mt-5">
  <div class = "row">
   <div class="mx-suto">  
<p>CopyRight Infratop.inc</p>
   </div>
  </div>
 </div>
</footer>
</body>

app/views/homes/top.html.erb
<!DOCTYPE html>
<body>
 <div class="container">
  <div class = "row">
   <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
 <h2>In <i class="fas fa-book"></i>Bookers,</h2>
 <p>you can share and exchange your opinions , inpressions , and emotions
about various books!</p>
<div class="btn-wrapper col-10 mx-auto">
 <div class="row">
<%= link_to 'Log in', new_user_session_path,class: "btn btn-info btn-sm btn-block md-3" %>
</div>
<div class="row">
<%= link_to 'Sign up', new_user_registration_path,class: "btn btn-success btn-sm btn-block md-3" %>
</div>
</div>
<footer>
<p>CopyRight Infratop.inc</p>
</footer>
    </div>
   </div>
 </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/b88cbfadf5.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i>
                Users
              <% end %>
            </li>
            <%= link_to books_path, class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i>
                Books
              <% end %>
            </li>
            <li class="nav-item">
            <%= link_to destroy_user_session_path,method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>
                Log out
              <% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "/", class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>
                Home
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path, class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i>
                About
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>
                Sign up
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>
                Log in
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <div class="Notification">
 　　　　<% flash.each do |key, value| %>
 　　　<%= content_tag :div, value, class: key %>
 　  　<% end %>
　　　</div>
    <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
 <div class = "row">
   <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h2>User info</h2>
 <div class ="form-group">
  <h3>Name</h3>
<% if @user.errors.any? %>
  <%= @user.errors.count %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 <%= form_with model: @user do |f| %>
  <%= f.label :Name %></br>
  <%= f.text_field :name %>
 
 <div class ="form-group">
   <h4>image</h4>
   <li>
    <%= f.file_field :profile_image, accept: "image/*" %>
  </li>
  </div>
  <div class ="form-group">
    <h5>introduction</h5>
    <%= f.text_area :introduction %>
  </div>
  <%= f.submit 'Update User' %>
　<% end %>
　  </div>
　 </div>
　</div>
　</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<div class="container px-5 px-sm-0">
    <div class = "row">
  <div class="col-md-3">
    <h1>Users info</h1>
    <h3 class="profile-name"></h3>
      <%= image_tag current_user.get_profile_image(100,100) %>
      <table class="table">
      <tr>
        <th>name</th>
         <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= current_user.introduction %></th>
      </tr>
      </table>
  <script src="https://kit.fontawesome.com/b88cbfadf5.js" crossorigin="anonymous"></script>
  <li class="nav-item">
    <%= link_to edit_user_path(current_user.id) ,class:"btn btn-info btn-sm btn-block md-3" do  %>
    <i class="fas fa-users"></i>
    <i class="fas fa-user-cog"></i>
    <% end %>
  </li>
    <h3>New book</h3>
    <%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Opinion</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book', class:"btn btn-success"%>
<% end %>  
  </div>
  <!--<div class="col-md-3">-->
    
  <!--</div>-->
  <div class="col-md-8 offset-md-1">
  <h5>Users</h5>
  <table class="table table-hover table-inverse">
    <tr>
      <th>image</th>
      <th>name</th>
    </tr>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(80,80) %>
        </td>
        <td> <%= user.name %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
 </div> 
 </div>
</div>

<!-- ユーザーの投稿一覧 -->
<%#= render 'books/book', books: @books %>
<p>CopyRight Infratop.inc</p>

app/views/users/show.html.erb
<!DOCTYPE html>
<div class="container px-5 px-sm-0">
  <div class = "row">
    <div class="col-md-3">
      <h1>Users info</h1>
      <h3 class="profile-name"></h3>
      <%= image_tag @user.get_profile_image(100,100) %>
      <table class="table">
        <tr>
          <th>name</th>
          <th><%= @user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= @user.introduction %></th>
        </tr>
      </table>
      <script src="https://kit.fontawesome.com/b88cbfadf5.js" crossorigin="anonymous"></script>
      <li class="nav-item">
        <%= link_to edit_user_path, class:"btn btn-info btn-sm btn-block md-3" do %>
        <i class="fas fa-users"></i>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </li>
    
  <!--<div class="col-md-3">-->
      <h3>New book</h3>
      <%= form_with model: Book.new do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
      	
        <h4>Opinion</h4>
        <%= f.text_area :body %>
      	
        <%= f.submit 'Create Book', class:"btn btn-success" %>
      <% end %>
    </div>
<!--</div>-->
    <div class="col-md-8 offset-md-1">
      <h5>Books</h5>
      <table class="table table-hover table-inverse">
        <tr>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= image_tag book.user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div> 
</div>
<!-- ユーザーの投稿一覧 -->
<%#= render 'books/book', books: @books %>
<p>CopyRight Infratop.inc</p>